name: DisableVillagerTrade
version: '${project.version}'
main: me.dodo.disablevillagertrade.DisableVillagerTrade
api-version: '1.21'
authors:
  - dodo
description: A lightweight plugin to prevent players from trading with villagers.
website: https://github.com/dodoflix/DisableVillagerTrade

permissions:
  disabletrade.bypass:
    description: Allows the player to bypass the trade block and trade with villagers.
    default: op
  disabletrade.update:
    description: Receives update notifications when a new version is available.
    default: op
